config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :posts do
    collection do
      post :confirm
    end
  end
  resources :users
  resources :favorites, only: [:index, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :content, length: { in: 1..250 }
  #   validates :image, presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  validates :name, presence: true, uniqueness: true, length: { maximum: 30 }
  validates :email, presence: true, uniqueness: true,  length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :posts
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
  # def initial_value
  #   @init = "#{current_user.name}, Let's share to all "
  # end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorites = current_user.favorite_posts
  end

  def create
    favorite = current_user.favorites.create(post_id: params[:post_id])
    redirect_to posts_path, notice: "#{favorite.post.user.name}'s post has been added to favorites"
  end

  def destroy
    favorite = current_user.favorites.find_by(post_id: params[:id]).destroy
    redirect_to posts_path, notice: "#{favorite.post.user.name} Unpostged Mr.'s post"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :set_post, only: [:show, :edit, :update, :destroy]
include PostsHelper
# before_action :initial_value, only: [:index, :new, :edit]
before_action :correct_user, only: [:edit, :update, :destroy]
  
  def index
    @posts = Post.all
  end
  
  def new
    if params[:back]
      @post = current_user.posts.new(post_params)
    else
      @post = current_user.posts.new
    end
  end
  
  def edit
  end
  
  def show
    @favorite = current_user.favorites.find_by(post_id: @post.id)
    @favorites = current_user.favorite_posts
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if params[:back]
      render :new
    else
      if @post.save
        PostMailer.post_mail(@post).deliver
        redirect_to posts_path(current_user.id), notice: "new post  was successfully created"
      else
        render :new
      end
    end
  end
  
  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "post edited"
    else
      render :edit
    end
  end
  
  def destroy
    @post.destroy
    redirect_to user_path(current_user.id), notice:"I deleted the post"
  end

  def confirm
    @post = current_user.posts.build(post_params)
    render :new if @post.invalid?
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :content, :image, :image_cache)
  end
  
  def set_post
    @post = Post.find(params[:id])
  end

  def correct_user
    @posts = current_user.posts.find_by(id: params[:id])
    redirect_to posts_path, notice: "Not Authorized to Edit this post" if @post.nil?
  end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :login_required, only: [:new, :create]  
  def new
  end
  def create
    user = User.find_by(email: session_params[:email].downcase)
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to posts_path
    else
      flash.now[:danger] = 'I failed to login'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash.now[:notice] = "Have been Logging out"
    redirect_to new_session_path
  end
  private
  def session_params
    params.require(:session).permit(:email, :password)
  end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :login_required, only: [:new, :create]
before_action :set_user, only: [:show, :edit, :update, :destroy]
before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit 
  end

  def show
    posts = current_user.posts.where.not(image: nil)
    @posts = current_user.posts.all.order("id DESC")
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to new_session_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_correct_user
    post = Post.find(params[:id]) 
    if current_user.id != post.user_id
      redirect_to posts_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end    
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<h1>favorites</h1>
<div class="main container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-3">
    </div>
    <div class="col-xs-12 col-sm-8 col-md-6">
      <ul class="list-inline list-unstyled">
        <% @favorites.each do |favorite| %>
        <div class="stories panel panel-default">
          <div class="post_image">
          <%= favorite.content %>
            <% if favorite.image.present? %>
              <%= image_tag(favorite.image.url, class: "img-responsive") %>
            <% end %>
          </div>
        </div>
        <% if favorite.present? %>
          <%= link_to 'Remove favorite', favorite_path(id: favorite.id), method: :delete, class: 'btn btn-danger' %>
        <% else %>
          <%= link_to 'Favorite', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
        <% end %>
        <li class="right"><%= link_to "Home", posts_path %></li>
        <% end %>  
      </ul>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-3">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instante</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
    <header>
     <ul class="panel-header  list-inline list-unstyled "> 
       <li class="h-inst">
         <h1 class="instante">Instante</h1>
       </li>
       <li class="h-search">
       <%= form_with url: "/search", method: :get do |form| %>
       <%= form.text_field :query, placeholder:"Search", class: "search-field" %>
         <i class="bi bi-search"></i><%= form.submit "Search", class: "search-btn" %>
       <% end %>
       </li> 
       
       <li class="h-icons">
         <li class="right"><i class="bi bi-house-fill"></i><%=link_to "Home", posts_path %></li>
         <li class="right"><i class="bi bi-messenger"></i><%=link_to "Message", posts_path %></li>
         <li class="right"><%=link_to "Random", posts_path %></li>
         <li class="right"><i class="bi bi-suit-heart"></i><%=link_to "favorites", favorites_path %></li>
         <li class="right"><i class="bi bi-person-circle"></i><%=link_to "Profile", user_path(current_user.id) %></li>
         <li class="right"><i class="bi bi-box-arrow-in-left"></i><%=link_to "Log out", session_path(current_user.id), method: :delete %></li>
       </li>
     </ul>
    </header>
    <% end %>  
    <% flash.each do |key, value| %> 
      <%= content_tag(:div, value, class: "#{key}") %> 
    <% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="post_form">
<% if @post.errors.any? %>
  <div class="" id="error_explanation">
    <h2><%= @post.errors.count %> prohibited this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
</div>
<ul class="list-inline list-unstyled">
  <li><p class="post_username"><%= current_user.name %></li>
</ul>
<%= form_with(model: @post, url: choose_new_or_edit, local: true) do |form| %> 
  <div class="post_image">
  <%= image_tag(@post.image.url, class: "img-responsive") if @post.image && @post.image.url %>
  </div>  
  <div class="form_group lead">
  <%= form.text_area :content, id: :post_content, placeholder: "#{current_user.name}, Let's share to all ", rows: 7, class: "form-control post_content" %>
  </div>
  <div class="image_upload panel panel-default">
    <ul class="list-inline list-unstyled">
      <li class="right">
      <% if (@post.content || @post.image).present? %>
        <p><strong><%= link_to "Delete", post_path(@post.id), method: :delete, data: {confirm: 'Are you sure to delete？'} %></strong></p>
      <% end %>
      </li>
      <li class="right">
        <label class="filelabel" title="Choose file">
          <%= image_tag("logos/image_icon.png", width: '25', height: '20') %>
          <%= form.file_field :image, id: :post_image  %>
          <%= form.hidden_field :image_cache %>
        </label>
      <% if @post.image.present? %>
      <li class="right"><p class="selected">selected</p></li>
      <% else %>
      <li class="right"><p class="not_selected"> No selected</p></li>
      <% end %>
      </li>
      <li class="left"><strong>Add post to<%#= link_to "Add post to", "#"%></strong>
      </li>
    </ul>
  </div>  
  <label class="send btn btn-default btn-block">
    <div>
      <%= form.submit "post", class: "send" %>post
    </div>
  </label>
<% end %>

app/views/posts/confirm.html.erb
<div class="post_form">
<% if @post.errors.any? %>
  <div class="" id="error_explanation">
    <h2><%= @post.errors.count %> prohibited this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
</div>
<div class="stories panel panel-default">
  <ul class="list-inline list-unstyled">
    <li><p class="post_username"><%= current_user.name %></li>
  </ul>
  <%= form_with(model: @post, url: choose_new_or_edit, local: true) do |form| %> 
    <div class="post_image">
    <%= image_tag(@post.image.url, class: "img-responsive") if @post.image && @post.image.url %>
    </div>  
    <div class="form_group lead">
    <%= form.text_area :content, id: :post_content, placeholder: "#{current_user.name}, Let's share to all ", rows: 7, class: "form-control post_content" %>
    </div>
</div>    
  <div class="image_upload panel panel-default">
    <ul class="list-inline list-unstyled">
      <li class="right">
        <label class="filelabel" title="Choose file">
          <%= image_tag("logos/image_icon.png", width: '25', height: '20') %>
          <%= form.hidden_field :image_cache %>
        </label>
      <% if @post.image.present? %>
      <li class="right"><p class="selected">selected</p></li>
      <% else %>
      <li class="right"><p class="not_selected"> No selected</p></li>
      <% end %>
    </ul>
  </div>  
  <label class="send btn btn-default btn-block">
    <div>
      <%= form.submit "post", class: "send" %>post
    </div>
  </label>
<% end %>

app/views/posts/edit.html.erb
<div class="main container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6">
      <div class="panel panel-default">
        <h3>Edit a post</h3>
        <%= render 'form' %>
        <%= link_to 'Show', @post %> 
        <%= link_to 'Back', posts_path %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-3">
    </div>
    <div class="col-xs-12 col-sm-8 col-md-6">
      <div class="stories panel panel-default">
        <div class="lead">
          <i class="bi bi-file-person-fill"></i><%= link_to "#{current_user.name} ", new_post_path %>
        </div>
        <ul class="list-inline list-unstyled">
          <li><i class="bi bi-camera-video-fill"></i><% link_to "Live Video", "#" %>Live Video</li>
          <li><i class="bi bi-images"></i><% link_to "Photos / Videos", "#" %>Photos / Videos</li>
          <li><i class="bi bi-window"></i><% link_to "Mood / Activity", "#" %>Mood / Activity</li>
        </ul>
      </div>
      <% @posts.each do |post| %>
        <div class="post panel panel-default">
          <ul class="list-inline list-unstyled">
            <li><p class="post_username"><%= link_to "#{post.user.name} #{post.user_id}", post_path(post.id) %></p></li>  
            <li><p id="post_index">Post</p></li>  
          </ul>
          <p class="post_timestamp"><small><%=  post.updated_at.strftime("%Y-%m-%d %H:%M")%></small></p> 
          <p class="post_content lead"><%= post.content %></p> 
          <div class="post_image">
            <% if post.image.present? %>
              <%= image_tag(post.image.url, class: "img-responsive") %>
            <% end %>
          </div>
            <ul class="list-inline list-unstyled">
              <li><i class="bi bi-hand-thumbs-up-fill"></i><%= link_to 'Favorite', favorites_path(post_id: post.id), method: :post %></li> 
              <li><%= link_to "Comment", "#" %></li> 
              <li><%= link_to "details", post_path(post.id) %></li> 
            </ul>
        </div>
      <% end %>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-3">
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6">
      <div class="panel panel-default">
        <h3>Create a post</h3>
        <%= render 'form' %> 
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6">
      <div class="my_post panel panel-default">
        <h3>Post</h3>
      </div>
      <div class="panel panel-default">
        <ul class="list-inline list-unstyled">
          <li><p class="bi bi-person-fill" class="post_username"><%= @post.user.name %></p></li>
          <p class="post_timestamp"><small><%= @post.updated_at.strftime("%Y-%m-%d %H:%M") %></small></p>
          <p class="post_content lead"><%= @post.content %></p>
          <div class="post_image">
            <strong>Image:</strong>
            <% if @post.image.present? %>
              <%= image_tag(@post.image.url, class: "img-responsive") %>
            <% end %>
          </div>
          <div>
            <strong>Title:</strong>
            <%= @post.title %>
          </div>
          <div>
            <strong>Content:</strong>
            <%= @post.content %>
          </div>
          <li class="right">
            <%= link_to 'Favorite', favorites_path(post_id: @post.id), method: :post %>
            <% if current_user.id == @post.user_id %>
              <li class="right"><%= link_to "Edit", edit_post_path(@post.id) %></li>
            <% end %>
          </li>
          <% if @post.user_id != current_user.id %>
            <% if @favorite.present? %>
              <%= link_to 'Remove favorite', favorite_path(id: @post.id), method: :delete, class: 'btn btn-danger' %>
            <% else %>
              <%= link_to 'Favorite', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
            <% end %>
          <% end %>
          <li class="right"><%= link_to "Home", posts_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="">
  <% if @user.errors.any? %>
    <div class="" id="error_explanation">
      <h2><%=pluralize(@user.errors.count, "error") %>prohibited<%= @user.name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>
<%= form_with(model: @user, local: true) do |form| %>
<% if @user.image.present? %>
  <label class="filelabel" title="Choose file">
    <%= image_tag(@user.image.url, class: "img-responsive") if @user.image && @user.image.url %>
    <%= form.file_field :image, id: :user_image %>
    <%= form.hidden_field :image_cache %>
  </label>
<% else %>
  <label class="filelabel" title="Choose file">
  <%= image_tag("logos/image_icon.png", width: '100', height: '100') %>
  <%= form.file_field :image, id: :user_image %>
  <%= image_tag(@user.image.url, class: "img-responsive") if @user.image && @user.image.url %>
  <%= form.hidden_field :image_cache %> 
  </label>
<% end %>
<div class="form_group" >
  <%= form.text_field :name, placeholder: "Name", rows: 7, class: "form-control" %>
</div>
<div class="form_group" >
  <%= form.text_field :email, placeholder: "e-mail", rows: 7, class: "form-control" %>
</div>
<div class="form_group" >
  <%= form.password_field :password, placeholder: "Password", rows: 7, class: "form-control" %>
</div>
<div class="form_group" >
  <%= form.password_field :password_confirmation, placeholder: "Password confirm", rows: 7, class: "form-control" %>
</div>
<label class="send btn btn-default btn-block">
  <div>
    <%= form.submit "Sign Up", class: "send"%> Sign up
  </div>
</label>
<% end %>

app/views/users/edit.html.erb
<div class="container-fluid">
  <div class="row-signup">
    <div class="col-xs-12 col-sm-8 col-md-6 align-items-center">
      <div class="panel panel-default">
        <h1>Account information</h1>
        <br>
        <%= render 'form', user: @user %>
        <div class="links-edit">
          <ul>
            <li><%= link_to 'Profile', @user %></li>
            <li><%= link_to 'Home', posts_path %></li>
            <li><%= link_to 'Delete Account', @user, method: :delete %></li>
        </div>
    </div>
  </div>
  <div class="footer">
    <div class="links">
      <ul class="text-muted">
        <li><% link_to "About", "#" %>About</li>
        <li><% link_to "Blog", "#" %>Blog</li>
        <li><% link_to "Jobs", "#" %>Jobs</li>
        <li><% link_to "Help", "#" %>Help</li>
        <li><% link_to "API", "#" %>API</li>
        <li><% link_to "Privacy", "#" %>Privacy</li>
        <li><% link_to "Terms", "#" %>Terms</li>
        <li><% link_to "Top Accounts", "#" %>Top Accounts</li>
        <li><% link_to "Hashtags", "#" %>Hashtags</li>
        <li><% link_to "Location", "#" %>Location</li>
        <li><% link_to "Instagram Lite", "#" %>Instagram Lite</li>
        <li><% link_to "English", "#" %>English</li>
      </ul>
    </div>
    <br>
    <div class="copyright text-muted">
      © 2021 Instagram from Facebook
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>User index new</h1>

app/views/users/new.html.erb
<div class="container-fluid">
  <div class="row-signup">
    <div class="col-xs-12 col-sm-8 col-md-6 align-items-center">
      <div class="panel panel-default">
        <h1 class="instante">Instante</h1>
        <br>
        <h3 class="text-muted">Sign up to see photos and videos from your friends.</h3>
        <%= render 'form', user: @user %>
        <p id="policy" class="text-muted">By signing up, you agree to our Terms, Data Policy and Cookies Policy.</p>
      </div> 
      <div id="login" class="panel panel-default">
        <p>Have and account? <%= link_to 'Log in', new_session_path %></p>
      </div>
      <div class="apps">
        <p>Get the app. </p>
        <div class="icons">
          <span>
            <%= image_tag("logos/apple_store.png", width: '120', height: '50') %>
            <%= image_tag("logos/google_store.png", width: '100', height: '80') %>
          </span>
        </div>
      </div> 
    </div>
  </div>
  <div class="footer">
    <div class="links">
      <ul class="text-muted">
        <li><% link_to "About", "#" %>About</li>
        <li><% link_to "Blog", "#" %>Blog</li>
        <li><% link_to "Jobs", "#" %>Jobs</li>
        <li><% link_to "Help", "#" %>Help</li>
        <li><% link_to "API", "#" %>API</li>
        <li><% link_to "Privacy", "#" %>Privacy</li>
        <li><% link_to "Terms", "#" %>Terms</li>
        <li><% link_to "Top Accounts", "#" %>Top Accounts</li>
        <li><% link_to "Hashtags", "#" %>Hashtags</li>
        <li><% link_to "Location", "#" %>Location</li>
        <li><% link_to "Instagram Lite", "#" %>Instagram Lite</li>
        <li><% link_to "English", "#" %>English</li>
      </ul>
    </div>
    <br>
    <div class="copyright text-muted">
      © 2021 Instagram from Facebook
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <h1>Users show</h1>
    <div class="col-xs-12 col-sm-8 col-md-6">
      <div class="panel panel-default">
        <h1>Instante</h1>
        <div class="Profile-info">
          <h1><strong>Image:</strong></h1>
          <div class="profile-img">
          <%= form_with(model: @user, local: true, method: :patch) do |form| %>
            <% if @user.image.present? %>
              <%= image_tag(@user.image.url, class: "img-responsive") if @user.image && @user.image.url %>
              <%= form.hidden_field :image_cache %> 
            <% else %>
              <label class="filelabel" title="Choose file">
              <%= image_tag("logos/image_icon.png", width: '100', height: '100') %>
              <%= form.file_field :image, id: :user_image %>
              <%= image_tag(@user.image.url, class: "img-responsive") if @user.image && @user.image.url %>
              <%= form.hidden_field :image_cache %> 
              </label>
            <% end %>
          <label class="send btn btn-default btn-block">
            <div>
            <%= form.submit "Profile", class: "send"%> Profile Image
            </div>
          </label>
          <% end %> 
          <p>
            <h1>
              <strong>Name:</strong>
              <%= @user.name %>
            </h1>
          </p>
          <p>
            <h1>
              <strong>Email:</strong>
              <%= @user.email %>
            </h1>
          </p>
        </div>
        <button type="button" class="btn btn-success"><%= link_to 'Edit', edit_user_path(@user) %></button> 
        <button type="button" class="btn btn-success"><%= link_to 'Post', new_post_path %></button>
        <button type="button" class="btn btn-success"><%= link_to 'favorites', favorites_path(@user) %></button>
      </div>  
    </div>
  </div>
</div>